import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Portofolio Faizz",
  description: "Generated by create next app",
  icons: {
    icon: "/faizz baru3.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/faizz baru3.png" />
      </head>
      <body
        className={`${jetbrainsMono.variable} antialiased`}>
          <Header />
          <StairTransition />
          <PageTransition>
            {children}
          </PageTransition>
      </body>
    </html>
  );
};
